import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:net';
import {planNativeDomain,applyNativeDomainPlan} from '../../../../ops/plus-v2/native-domain-bootstrap.mjs';
import {startNativeRuntime,readNativeRuntimeProfile} from '../../../../ops/plus-v2/runtime-host.mjs';
import {createNativeStorage} from '../../../apps/lwm-demo/src/native-storage.mjs';
import {planNativeIntake,createNativeIntakeCommand} from '../../../apps/lwm-demo/public-plus/native-intake.js';
import {planObservationImport,createObservationImportBatch,observationImportFields} from '../../../apps/lwm-demo/public-plus/observation-import.js';
import {createTaskDomainAccess} from '../../../apps/lwm-demo/src/task-access.mjs';
import {createMatterIntakeDomain} from '../../../apps/lwm-demo/src/matter-intake.mjs';
import {NativeOntologyCatalog,buildOntologyBundle,ontologyStorageSchema} from '../dist/index.js';
import {CelClient} from '../../actions/dist/index.js';
import {loadDomainPacks} from '../../api/dist/schema-loader.js';
import {fileURLToPath} from 'node:url';
import {buildTaskVerificationInput} from '../../../domain-packs/lwm-plus/mechanisms/task-verification.mjs';
import {buildTaskPriorityInput} from '../../../domain-packs/lwm-plus/mechanisms/task-priority.mjs';
import {buildTaskRulesInput} from '../../../domain-packs/lwm-plus/mechanisms/task-rules.mjs';
import {buildTaskSourceGovernanceInput} from '../../../domain-packs/lwm-plus/mechanisms/task-source-governance.mjs';
import {buildMatterIntakeInput} from '../../../domain-packs/lwm-plus/mechanisms/matter-intake.mjs';

const linux={skip:process.platform!=='linux',timeout:45000};
const json=p=>JSON.parse(readFileSync(p,'utf8'));
const source=(n=1)=>({matterNumber:'SYNTHETIC-'+n,title:'Source object '+n,jurisdiction:'TEST',currentState:'UNASSESSED',riskBand:'LOW',openedAt:new Date(Date.now()-5000).toISOString(),sourceSystem:'demo-matter',sourceRecordId:'record-'+n,sourceRevision:'1'});
async function fixture(t){
  const probe=createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const celPort=probe.address().port;await new Promise(r=>probe.close(r));
  const dir=mkdtempSync(join(tmpdir(),'plus-native-intake-')),plan=await planNativeDomain({schema:'plus-domain-bootstrap-request-v1',parentDir:dir,directoryName:'native',tenantId:'matter-intake-test',workspaceKey:'synthetic',ports:{control:0,workbench:0,cel:celPort},credentialHours:1});
  const receipt=await applyNativeDomainPlan(plan,plan.planHash),profile=readNativeRuntimeProfile(receipt.profilePath),storage=createNativeStorage(profile.dbPath),ctx={tenantId:profile.tenantId};let runtime;
  t.after(async()=>{await runtime?.close();storage.close();rmSync(dir,{recursive:true,force:true});});
  const start=async()=>{runtime=await startNativeRuntime(profile,{celBinary:process.env.LWM_CEL_BINARY});};await start();
  const token=role=>json(receipt.personalAccessFiles.find(p=>p.roles.includes(role)).path).token;
  const call=async(role,path,body,key='intake-native-key')=>{const r=await fetch(runtime.state().workbenchUrl+'/api'+path,{method:body?'POST':'GET',headers:{authorization:'Bearer '+token(role),...(body?{'content-type':'application/json','idempotency-key':key}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json()};};
  const api=role=>async(path,epoch,body,key)=>{const r=await call(role,path,body,key);if(r.status!==200)throw Object.assign(Error(r.body.error?.code??'HTTP_ERROR'),{status:r.status});return r.body.data;};
  const rows=async type=>(await storage.queryObjects(ctx,type,{and:[]},{limit:100})).items;
  return {dir,plan,receipt,profile,storage,ctx,call,api,rows,token,runtime:()=>runtime,async restart(){await runtime.close();await start();},policy:()=>json(profile.policyPath),save:value=>writeFileSync(profile.policyPath,JSON.stringify(value))};
}
test('empty production installation → source Matter → task → mapped JSON observation → independent verification with native links and reopen; no seed import',linux,async t=>{
  const f=await fixture(t),api=f.api('investigator'),catalog=await api('/ontology',1),input=source();
  assert.equal((await f.rows('Matter')).length,0);const command=createNativeIntakeCommand(planNativeIntake({kind:'MATTER',input,catalog}));await command.submit(api,1);
  const root=command.snapshot().reference;assert.equal(root.type,'Matter');const matter=await api('/objects/Matter/'+root.id,1);assert.equal(matter.object.dataClassification,'SYNTHETIC');assert.equal(matter.object.importSourceRecordId,input.sourceRecordId);
  for(const type of ['Observation','TaskCompletionVerification','PlusEvent','PlusExecution','PlusDefinitionRevision'])assert.equal((await f.rows(type)).length,0,type);
  const taskInput={taskNumber:'NATIVE-TASK',title:'SYNTHETIC collect evidence',priority:'LOW',assignee:'demo-investigator',instructions:'No inference from workflow state',dueAt:new Date(Date.now()+3600000).toISOString()};
  const taskCommand=createNativeIntakeCommand(planNativeIntake({kind:'TASK',input:taskInput,matter:matter.reference,catalog}));await taskCommand.submit(api,1);const task=await api('/objects/InvestigationTask/'+taskCommand.snapshot().reference.id,1);assert.equal(task.object.actualCompletion,'UNKNOWN');
  const eventTime=new Date(Date.now()-1000).toISOString(),record={title:'Imported report',summary:'SYNTHETIC unverified report',reportedCompletion:'DONE',eventTime,sourceRecordId:'new-report',sourceRevision:'1'};
  const reportPlan=planObservationImport({raw:JSON.stringify([record]),mapping:Object.fromEntries(observationImportFields.map(f=>[f,f])),sourceSystem:'demo-report',channelKey:'report',task:task.reference,catalog});
  const batch=createObservationImportBatch(reportPlan);await batch.run({api,epoch:1});assert.equal(batch.snapshot().entries[0].status,'COMMITTED');assert.equal((await api('/objects/InvestigationTask/'+task.reference.id,1)).object.actualCompletion,'UNKNOWN');
  const observation=(await f.rows('Observation'))[0];assert.equal((await f.rows('PlusEvent')).length,1);
  const check={task:task.reference.id,observation:observation._id,expectedVersion:task.reference.version,expectedObservationVersion:observation._version,result:'DONE',targetTime:eventTime,methodKey:'independent',evidence:'SYNTHETIC independent test assertion'};
  assert.equal((await f.call('investigator','/actions/NativeVerifyTaskObservation',check,'intake-check')).status,403);assert.equal((await f.call('data_reviewer','/actions/NativeVerifyTaskObservation',check,'intake-check')).status,200);
  const graph=await f.call('viewer','/objects/Matter/'+root.id+'/links?linkType=MatterTask&direction=outbound');assert.equal(graph.status,200);assert.equal(graph.body.data.items[0].neighbor.reference.id,task.reference.id);
  await f.restart();assert.equal((await f.call('viewer','/objects/InvestigationTask/'+task.reference.id)).body.data.object.actualCompletion,'DONE');assert.equal((await f.rows('Matter')).length,1);assert.equal((await f.rows('PlusExecution')).length,0);
  assert.ok((await f.rows('PlusOutbox')).length>=5);for(const file of ['native-intake.js','native-intake-ui.js'])assert.equal((await fetch(f.runtime().state().workbenchUrl+'/'+file)).status,200);
});
test('source idempotency, payload conflict, concurrent delivery, lost acknowledgement and current scope guards never create duplicate roots',linux,async t=>{
  const f=await fixture(t),input=source(),path='/actions/NativeImportTaskMatter';
  assert.equal((await f.call('viewer',path,input)).status,403);
  assert.equal((await f.call('investigator',path,{...input,workspaceKey:'other'})).status,400);
  assert.equal((await f.call('investigator',path,{...input,openedAt:'2026-02-30T00:00:00.000Z'})).status,400);
  assert.equal((await f.call('investigator',path,{...input,sourceSystem:'not-authorized'})).status,403);
  const first=await f.call('investigator',path,input);assert.equal(first.status,200,JSON.stringify(first));
  assert.equal((await f.call('investigator',path,input)).body.data.replayed,true);
  assert.equal((await f.call('investigator',path,{...input,title:'changed'})).status,409);
  assert.equal((await f.call('investigator',path,input,'different-request-key')).body.data.sourceReplay,true);
  assert.equal((await f.call('investigator',path,{...input,title:'changed'},'different-request-key')).status,409);
  assert.equal((await f.call('investigator',path,{...input,sourceRevision:'2'},'new-source-revision')).status,409,'correction is not a silent overwrite');
  const next=source(2),results=await Promise.all(['concurrent-key-a','concurrent-key-b'].map(key=>f.call('investigator',path,next,key)));assert.ok(results.some(r=>r.status===200));assert.ok(results.every(r=>[200,409].includes(r.status)));
  for(const key of ['concurrent-key-a','concurrent-key-b'])assert.equal((await f.call('investigator',path,next,key)).status,200);
  const api=f.api('investigator'),catalog=await api('/ontology',1),third=createNativeIntakeCommand(planNativeIntake({kind:'MATTER',input:source(3),catalog}));let lose=true;const keys=[];
  const transport=async(path,epoch,body,key)=>{const value=await api(path,epoch,body,key);if(body){keys.push(key);if(lose){lose=false;throw Object.assign(Error('lost response'),{status:502});}}return value;};
  await assert.rejects(()=>third.submit(transport,1));assert.equal(third.snapshot().status,'UNCERTAIN');await third.submit(transport,1);assert.equal(keys[0],keys[1]);assert.equal(third.snapshot().status,'REPLAYED');assert.equal((await f.rows('Matter')).length,3);
  const policy=f.policy(),grant=policy.taskDomain.grants.find(g=>g.actions.includes('NativeImportTaskMatter'));grant.workspaces=['other'];f.save(policy);
  assert.equal((await f.call('investigator',path,source(4),'wrong-workspace-key')).status,403,'create with no existing id still enforces grant workspace');
  assert.equal((await f.call('investigator',path,input)).status,403,'original receipt is reauthorized');
  grant.workspaces=['synthetic'];grant.types.Matter.write=grant.types.Matter.write.filter(f=>f!=='importContentHash');f.save(policy);assert.equal((await f.call('investigator',path,source(4),'missing-field-key')).status,403);
  assert.equal((await f.call('investigator','/actions/NativeImportMatter',input)).status,404,'retired route not revived');assert.equal((await f.rows('Matter')).length,3);
});
test('current source policy withdrawal during native staging rolls back root, command receipt and outbox atomically',linux,async t=>{
  const f=await fixture(t),p={id:'demo-investigator',tenantId:f.profile.tenantId,roles:['investigator']};let inject=true;
  const storage=new Proxy(f.storage,{get(target,key){if(key!=='beginTransaction')return target[key];return async(...args)=>{const tx=await target.beginTransaction(...args);return new Proxy(tx,{get(transaction,property){if(property!=='createObject')return transaction[property];return async(...values)=>{const value=await transaction.createObject(...values);if(inject&&values[0]==='NativeCommandReceipt'){inject=false;const policy=f.policy();delete policy.taskDomain.matterImportSources['demo-matter'];f.save(policy);}return value;};}});};}});
  const access=createTaskDomainAccess({storage,tenantId:p.tenantId,loadPolicy:f.policy,reauthenticate:async()=>{}}),catalog=new NativeOntologyCatalog({storage,tenantId:p.tenantId,authorize:async()=>true});
  const client=new CelClient({address:'127.0.0.1:'+f.profile.ports.cel,maxRetries:0,timeoutMs:2000});t.after(()=>client.close());
  const domain=createMatterIntakeDomain({storage,catalog,cel:client,tenantId:p.tenantId,...access}),before=(await f.rows('PlusOutbox')).length;
  await assert.rejects(()=>domain.execute(source(),p,'withdraw-in-stage-key'));
  assert.equal(inject,false,'reached actual transaction staging');assert.equal((await f.rows('Matter')).length,0);assert.equal((await f.rows('NativeCommandReceipt')).length,0);assert.equal((await f.rows('PlusOutbox')).length,before);
});

test('additive import is a normally reviewed native ontology publication, never revival of retired legacy action',linux,async t=>{
  const dir=mkdtempSync(join(tmpdir(),'plus-intake-publication-')),storage=createNativeStorage(join(dir,'platform.sqlite')),tenantId='intake-publication',ctx={tenantId};
  t.after(()=>{storage.close();rmSync(dir,{recursive:true,force:true});});
  const loaded=await loadDomainPacks(fileURLToPath(new URL('../../../domain-packs',import.meta.url)),['core','lwm-demo','lwm-plus','plus-core'],[]);
  const odl=loaded.packInfos.flatMap(p=>p.manifest.schema.map(path=>readFileSync(join(p.packDir,path),'utf8'))).join('\n');
  const baseline=buildTaskSourceGovernanceInput(buildTaskRulesInput(buildTaskPriorityInput(buildTaskVerificationInput({odl,manifests:{},disabledActions:loaded.parsed.actionTypes.map(a=>a.name)}),{initializePriority:true})));
  const initial=buildOntologyBundle(baseline);await storage.applySchema(ctx,ontologyStorageSchema(initial,1));
  const author={id:'schema-author',tenantId,roles:['data_reviewer']},owner={id:'schema-owner',tenantId,roles:['model_owner']};
  const catalog=new NativeOntologyCatalog({storage,tenantId,authorize:async p=>p.tenantId===tenantId&&[author.id,owner.id].includes(p.id)});await catalog.adoptInstalledBaseline(baseline,owner);
  const next=buildMatterIntakeInput(baseline),draft=await catalog.submit(next,author,'intake-publication',initial.contentHash),valid=await catalog.validate(draft._id,draft._version,author);
  await assert.rejects(()=>catalog.review(valid._id,valid._version,'APPROVE','self review',author),/INDEPENDENT/);
  await catalog.review(valid._id,valid._version,'APPROVE','Reviewed source/field/workspace intake contract',owner);
  const current=await catalog.read(owner);assert.equal(current.bundle.contentHash,buildOntologyBundle(next).contentHash);assert.equal(current.head.storageVersion,2);
  assert.ok(current.bundle.disabledActions.includes('NativeImportMatter'));assert.equal(Object.hasOwn(current.bundle.manifests,'NativeImportMatter'),false);assert.ok(current.bundle.manifests.NativeImportTaskMatter);
  assert.equal((await storage.queryObjects(ctx,'Matter',{and:[]},{limit:10})).items.length,0,'publication does not seed data');
});
