import {appendLearning} from './learning-ui.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=x=>JSON.stringify(x,null,2), pre=x=>`<pre>${esc(json(x))}</pre>`;
const $=x=>document.querySelector(x);
const sample=[{name:'保持低压力假设',schedule:[{requested_action:1,l:1,f:0,probe:0},{requested_action:1,l:1,f:0,probe:1}],costAct:2,costRefrain:8,interventionCost:0},{name:'提高压力假设',schedule:[{requested_action:1,l:1,f:1,probe:0},{requested_action:1,l:1,f:1,probe:1}],costAct:2,costRefrain:8,interventionCost:1}];
export function renderEngineering(kind,c){
  const disabled=r=>c.role(r)?'':'disabled';
  const bind=(s,f)=>{$(s)?.addEventListener('click',()=>void c.run(f));};
  if(kind==='scenarios'){
    const sim=c.selectedSimulation(),out=sim?JSON.parse(sim.outputJson):null,m=c.current();
    $('#content').innerHTML=`<section class="panel"><h2>独立动力学服务 · 非 Transformer</h2><div class="callout">工程服务状态：${c.state.plus.model.ready?'模型服务就绪，按原生注册表选择版本':'不可用，禁止以预置结果替代'}。<br>小型神经网络估计 R 行为机制；Bayes32 显式先验推断 H 观察；公开规则映射 E。不是完整工业级 LWM。</div><p>以下预填方案是可修改的合成假设，不是证据提取结果。l=公开法律效果状态，f=压力，requested_action=请求行为，probe=局部观察通道，均为 0/1；当前只支持同一机制族的 2 或 3 步比较。</p><label>依据证据<select id="sim-evidence">${c.evidence().filter(o=>o.verified).map(o=>`<option value="${esc(o._id)}">${esc(o.title+' / '+o.source)}</option>`).join('')||'<option value="">请先独立核验证据</option>'}</select></label><label>初始实际行为<select id="initial-action"><option value="0">0 / REFRAIN</option><option value="1">1 / ACT</option></select></label><label>方案及假设<textarea id="options" rows="9">${esc(json(sample))}</textarea></label><label>公开行为轨迹（0–24 条）<textarea id="behavior-context" rows="3">[]</textarea></label><p class="muted">字段：l、f、prev_action、requested_action、next_action。使用者须确认来自相同机制、可信且已获授权的历史轨迹。</p><label>公开观察轨迹（0–16 条）<textarea id="observation-context" rows="3">[]</textarea></label><p class="muted">字段：alignment、probe、outcome；outcome 为 OBSERVED_TRUE / OBSERVED_FALSE / MISSING。H 空轨迹采用明确先验；R 使用当前登记的神经版本。添加上下文不会自行训练或发布。</p><button id="simulate" class="primary" ${disabled('investigator')}>运行独立动力学推演</button></section><section class="panel"><h2>同一本体中的预测记录</h2><label>历史推演<select id="simulation-select">${c.simulations().map(s=>`<option value="${esc(s._id)}" ${s._id===sim?._id?'selected':''}>${esc(s.createdAt)}</option>`).join('')}</select></label>${out?`<div class="table-wrap"><table><thead><tr><th>方案</th><th>终态 ACT 概率</th><th>E 条件预测</th><th>期望成本</th></tr></thead><tbody>${out.options.map((o,i)=>`<tr><td>${esc(o.name)} ${i===out.recommendedIndex?'<span class="badge">最低期望成本</span>':''}</td><td>${(o.actProbability*100).toFixed(2)}%</td><td>${pre(o.finalE)}</td><td>${o.expectedCost.toFixed(4)}</td></tr>`).join('')}</tbody></table></div><p>${esc(out.model)} · ${out.parameters} 参数 · 当前工件 ${esc(out.modelHash?.slice(0,16))} / 基线 ${esc(out.checkpointHash?.slice(0,16))}</p><p>概率是在人工假设下的预测，不是置信区间或法律结论。E 的 NOT_PROVED 不得反写 R；当前神经工件由原生注册表选择；训练不能直接激活模型。</p><details><summary>模型、上下文、依据版本与完整输出</summary>${pre(out)}</details><div class="row"><label>人工选择方案<select id="planned-option">${out.options.map((o,i)=>`<option value="${i}" ${i===out.recommendedIndex?'selected':''}>${esc(o.name)}</option>`).join('')}</select></label><label>人工选择业务目标<select id="target-state">${({EVIDENCE_COMPLETE:['RETENTION_REQUIRED','MANUAL_REVIEW'],NOTICE_RECEIVED:['NOTICE_TIMELY','NOTICE_REQUIRES_CLARIFICATION'],CLAIM_RECEIVED:['RESPONSE_READY','MANUAL_REVIEW']}[m?.currentState]??[]).map(s=>`<option>${s}</option>`).join('')}</select></label></div><label>人工决策理由<input id="rationale" value="核对条件预测及证据后提出业务建议，仍需独立审批"></label><button id="propose" ${disabled('investigator')}>提交受治理提案</button>`:'<p>尚无预测；真实运行后才能提交对应提案。</p>'}</section>`;
    bind('#simulate',async()=>{if(!m)throw new Error('请先导入并选择业务对象');c.notify('正在调用独立模型服务…');const result=await c.command('simulate',{matter:m._id,observation:$('#sim-evidence').value,expectedVersion:m._version,initialAction:Number($('#initial-action').value),options:JSON.parse($('#options').value),behaviorDemonstrations:JSON.parse($('#behavior-context').value),observationDemonstrations:JSON.parse($('#observation-context').value)});c.setSimulation(result.receipt.resultId);});
    $('#simulation-select').onchange=()=>c.setSimulation($('#simulation-select').value);
    bind('#propose',async()=>{await c.command('propose',{simulation:sim._id,optionIndex:Number($('#planned-option').value),toState:$('#target-state').value,rationale:$('#rationale').value});c.go('actions');});
    return;
  }
  const outcomes=c.items('OutcomeRecord');
  $('#content').innerHTML=`<section class="panel"><h2>模型登记与学习边界</h2>${pre(c.state.plus.model)}<div class="callout warning">当前真实实现：独立轨迹核验、机制组分区、冻结数据集、260 个神经参数更新、评测、独立发布与回滚。<br>尚未证明：真实业务效果与工业可靠性。H/E 不随 R 神经更新自动改变，合成演示不能冒充业务收益。</div></section><section class="panel"><h2>业务结果与独立核验</h2><p>结果核实不等于训练资格通过；补充完整轨迹并独立核对时序、分组、采集协议和隐私后，才可形成下方的训练样本。</p><div class="row"><label>已执行方案的推演<select id="outcome-sim">${c.simulations().map(s=>`<option value="${s._id}">${esc(s.createdAt)}</option>`).join('')}</select></label><label>实际采用方案序号<select id="outcome-option">${[0,1,2,3].map(i=>`<option value="${i}">${i}</option>`).join('')}</select></label><label>终态实际行为<select id="actual"><option value="0">0 / REFRAIN</option><option value="1">1 / ACT</option></select></label></div><label>结果来源及核验方法<input id="outcome-evidence"></label><button id="record-outcome" ${disabled('investigator')}>记录待核验结果</button><label>独立核验说明<input id="qualification-note"></label><label><span>隐私与使用授权已核验</span><input id="privacy" type="checkbox"></label>${outcomes.map(o=>`<article><p>${esc(o.evidence)} · ${esc(o.status)}</p>${o.status==='HELD'?`<button data-qualify="${o._id}" ${disabled('data_reviewer')}>核实业务结果</button>`:''}${o.status!=='WITHDRAWN'?`<button data-withdraw="${o._id}" ${disabled('data_reviewer')}>撤回结果资格</button>`:''}</article>`).join('')}</section>`;
  bind('#record-outcome',async()=>c.command('recordOutcome',{simulation:$('#outcome-sim').value,optionIndex:Number($('#outcome-option').value),actual:Number($('#actual').value),evidence:$('#outcome-evidence').value}));
  document.querySelectorAll('[data-qualify]').forEach(b=>b.onclick=()=>void c.run(()=>c.command('qualifyOutcome',{id:b.dataset.qualify,note:$('#qualification-note').value,privacyConfirmed:$('#privacy').checked})));
  document.querySelectorAll('[data-withdraw]').forEach(b=>b.onclick=()=>void c.run(()=>c.command('withdrawOutcome',{id:b.dataset.withdraw,note:$('#qualification-note').value})));
  appendLearning(c);
}
